export type ProductStatus = "verified" | "prototype" | "fixed" | "repair" | "deferred";

export type AuditedProduct = {
  code: string;
  titleZh: string;
  titleEn: string;
  status: ProductStatus;
  statusZh: string;
  statusEn: string;
  actualZh: string;
  actualEn: string;
  boundaryZh: string;
  boundaryEn: string;
  motionZh: string;
  motionEn: string;
  repo: string;
};

export type ProductFamily = {
  id: string;
  index: string;
  titleZh: string;
  titleEn: string;
  introZh: string;
  introEn: string;
  products: AuditedProduct[];
};

export const productFamilies: ProductFamily[] = [
  {
    id: "semantic-firewall",
    index: "01",
    titleZh: "語意防火牆系統族",
    titleEn: "Semantic Firewall Family",
    introZh: "不是六套同質的 AI 引擎，而是總體原型、規則掃描、反詐治理、固定案例與領域邊界的不同層級。",
    introEn: "Not six equivalent AI engines, but distinct layers: system concept, rule scanning, anti-scam governance, fixed cases and domain boundaries.",
    products: [
      {
        code: "SF-01",
        titleZh: "Semantic Firewall V4",
        titleEn: "Semantic Firewall V4",
        status: "prototype",
        statusZh: "三層前端原型",
        statusEn: "THREE-LAYER PROTOTYPE",
        actualZh: "以 Regex 加分呈現文字風險、Audit 摘要與概念鎖的三層式純前端試驗台。",
        actualEn: "A three-layer front-end lab using regex scoring for text risk, an audit summary and a conceptual lock.",
        boundaryZh: "沒有完整後端風控、商業 API、真實輸出遮罩或安全身分驗證。",
        boundaryEn: "No production risk backend, commercial API, real output masking or secure identity verification.",
        motionZh: "可用 LOGO 三重漣漪呈現 Regex Shield → Audit → LOCKED；核心不假裝自動解鎖。",
        motionEn: "Three logo ripples can show Regex Shield → Audit → LOCKED, with the core never faking an unlock.",
        repo: "https://github.com/HIJO790401/-8888-Semantic-Firewall-SystemV4",
      },
      {
        code: "SF-02",
        titleZh: "反詐騙語意鎖 R-Lock",
        titleEn: "Anti-Scam Semantic R-Lock",
        status: "verified",
        statusZh: "已核實本地規則引擎",
        statusEn: "VERIFIED LOCAL RULE ENGINE",
        actualZh: "本地 deterministic 流程輸出 SCBKR、R-Lock、VOID 狀態、行動閘門與 SHA-256 治理結構指紋。",
        actualEn: "A deterministic local flow producing SCBKR, R-Lock, VOID states, an action gate and a SHA-256 governance-structure fingerprint.",
        boundaryZh: "沒有外部 AI、銀行／政府查核、詐騙準確率或交易封鎖能力；hash 不是事件真偽證明。",
        boundaryEn: "No external AI, bank or government verification, accuracy claim or transaction blocking; the hash does not prove event truth.",
        motionZh: "使用 Repo 既有假銀行案例，實際跑現有函式；畫面固定標示 LOCAL ENGINE · NO EXTERNAL AI。",
        motionEn: "Run the repository's bank-scam fixture through real functions and label it LOCAL ENGINE · NO EXTERNAL AI.",
        repo: "https://github.com/HIJO790401/anti-scam-semantic-rlock",
      },
      {
        code: "SF-03",
        titleZh: "反詐騙語意防火牆 Non R-Lock",
        titleEn: "Anti-Scam Semantic Firewall · Non R-Lock",
        status: "repair",
        statusZh: "已驗證失敗／待修復",
        statusEn: "VERIFIED FAILURE · REPAIR",
        actualZh: "規則核心含六個內建案例與 SAFE／RISK／FATAL／NON-CLOSABLE 分流。",
        actualEn: "Its rule core includes six fixtures and SAFE, RISK, FATAL and NON-CLOSABLE routing.",
        boundaryZh: "目前 index.html 有 await 語法位置錯誤與重複 input id，現有 UI 不能宣稱正常運作。",
        boundaryEn: "The current index has an invalid await position and duplicate input IDs, so the UI cannot be presented as working.",
        motionZh: "先修互動層，再讓六個內建案例呼叫真實 analyzeMessage()；本階段只標概念流程。",
        motionEn: "Repair the UI first, then run all six fixtures through analyzeMessage(); for now it remains a concept flow.",
        repo: "https://github.com/HIJO790401/anti-scam-semantic-firewall",
      },
      {
        code: "SF-04",
        titleZh: "Prompt／算力治理掃描器",
        titleEn: "Prompt & Compute Governance Scanner",
        status: "prototype",
        statusZh: "瀏覽器規則掃描原型",
        statusEn: "BROWSER RULE-SCAN PROTOTYPE",
        actualZh: "以字詞命中、SCBKR 布林欄與固定公式輸出 SPI、風險級別及估算成本。",
        actualEn: "Keyword matches, SCBKR booleans and fixed formulas produce SPI, risk grades and an estimated cost.",
        boundaryZh: "不驗證事實；成本不是帳單，模型 offset 不是 benchmark，Author Shield 目前未實際掛入入口函式。",
        boundaryEn: "It does not fact-check; cost is not billing, model offsets are not benchmarks, and Author Shield is not wired to the active entry point.",
        motionZh: "固定 DEMO 文字 → 真實命中詞 → SCBKR → SPI 加法；成本必須標示 Estimate。",
        motionEn: "Fixture text → real keyword hits → SCBKR → SPI additions, with all cost figures labeled Estimate.",
        repo: "https://github.com/HIJO790401/semantic-firewall-system",
      },
      {
        code: "SF-05",
        titleZh: "語意防火牆雙引擎展示",
        titleEn: "Semantic Firewall Dual-Engine Display",
        status: "fixed",
        statusZh: "兩個固定案例",
        statusEn: "TWO FIXED CASES",
        actualZh: "法律責任敘事與成本敘事兩組預寫案例，可切換中英文、開啟完整內容並用瀏覽器 TTS 朗讀。",
        actualEn: "Two prewritten legal-responsibility and cost-narrative cases with bilingual switching, detailed views and browser TTS.",
        boundaryZh: "沒有任意案件分析、證據查核、runtime 推論或可呼叫的正式 API。",
        boundaryEn: "No arbitrary-case analysis, evidence verification, runtime inference or callable production API.",
        motionZh: "以 LOGO 雙環展開 A／B 固定案例，API 區明確標示 STATIC OUTPUT FORMAT PREVIEW。",
        motionEn: "Use the logo's dual rings for the two fixed cases and mark the API panel STATIC OUTPUT FORMAT PREVIEW.",
        repo: "https://github.com/HIJO790401/semantic-firewall-dual-engine-demo",
      },
      {
        code: "SF-06",
        titleZh: "著作權 SCBKR 責任邊界引擎",
        titleEn: "Copyright SCBKR Boundary Engine",
        status: "fixed",
        statusZh: "固定 3×4 責任矩陣",
        statusEn: "FIXED 3×4 RESPONSIBILITY MATRIX",
        actualZh: "三種授權情境乘四種用途，依既有矩陣輸出狀態、邊界、失敗條件、責任錨與 SHA-256 選項指紋。",
        actualEn: "Three license scenarios by four uses produce matrix-defined states, boundaries, failure conditions, anchors and a SHA-256 option fingerprint.",
        boundaryZh: "不讀作品或合約、不查權利人、不做侵權終判；hash 不能證明版權或原創性。",
        boundaryEn: "It reads no work or contract, checks no owner and makes no infringement ruling; the hash cannot prove copyright or originality.",
        motionZh: "直接沿用 Repo 已有 Auto Demo 判決順序，不新增法律能力或改寫結果。",
        motionEn: "Preserve the repository's existing Auto Demo verdict order without adding legal capability or altering results.",
        repo: "https://github.com/HIJO790401/copyright-scbkr-engine",
      },
    ],
  },
  {
    id: "responsibility-governance",
    index: "02",
    titleZh: "責任鏈與決策治理",
    titleEn: "Responsibility & Decision Governance",
    introZh: "這一族處理草稿簽收、記憶索引、文件權限、決策資格、付款責任與語意支持邊界；每套系統的輸入能力並不相同。",
    introEn: "This family covers draft acceptance, memory indexing, document rights, decision eligibility, payment responsibility and semantic-support boundaries, each with a different input surface.",
    products: [
      {
        code: "RG-01",
        titleZh: "SCBKR 本地責任鏈模型",
        titleEn: "SCBKR Local Responsibility Model",
        status: "deferred",
        statusZh: "核實完成／動畫暫緩",
        statusEn: "VERIFIED · MOTION DEFERRED",
        actualZh: "把原始需求編成 SCBKR 草稿，經使用者簽名、生成、驗收與二次確認後才寫入四庫；VECTOR 只負責召回。",
        actualEn: "Raw requests become SCBKR drafts and enter four stores only after user signature, generation, acceptance and reconfirmation; VECTOR is recall-only.",
        boundaryZh: "不是底層模型、自動理解、自動終裁或自動入庫；97.9% 是字數換算估計，且低於程式 98.06% 門檻。",
        boundaryEn: "Not a base model, automatic understanding, autonomous judge or auto-storage system; 97.9% is a character-derived estimate below the code's 98.06% gate.",
        motionZh: "依 Owner 指示，責任鏈模型動畫本階段暫緩；先保留可驗證的系統說明。",
        motionEn: "Per the Owner's instruction, motion is deferred in this phase while the verified system explanation remains visible.",
        repo: "https://github.com/HIJO790401/scbkr-local-responsibility-model",
      },
      {
        code: "RG-02",
        titleZh: "SCBKR Memory Index",
        titleEn: "SCBKR Memory Index",
        status: "deferred",
        statusZh: "索引層／動畫暫緩",
        statusEn: "INDEX LAYER · MOTION DEFERRED",
        actualZh: "CLI 依檔名、路徑與 mtime 建 metadata，通過 B／R／K 閘門後輸出 decision-ready JSON，並提供本機關鍵字查詢。",
        actualEn: "A CLI builds metadata from filename, path and mtime, emits decision-ready JSON after B/R/K gates and serves local keyword search.",
        boundaryZh: "不讀文件內容，不是向量／語意搜尋；ASCII tokenizer 對中文查詢不可靠。",
        boundaryEn: "It does not read file contents and is not vector or semantic search; its ASCII-oriented tokenizer is unreliable for Chinese queries.",
        motionZh: "先把內容索引與中文查詢邊界修清楚，再製作動畫。",
        motionEn: "Clarify content-indexing and Chinese-query boundaries before producing motion.",
        repo: "https://github.com/HIJO790401/scbkr-memory-index",
      },
      {
        code: "RG-03",
        titleZh: "WIF 決策資格審計展示",
        titleEn: "WIF Decision Eligibility Audit Display",
        status: "fixed",
        statusZh: "九個策展固定案例",
        statusEn: "NINE CURATED FIXTURES",
        actualZh: "Website／Image／Finance 各三案，展示 Compiler、CAL、SCBKR、R-Lock、VOID、驗證缺口與 Action Gate。",
        actualEn: "Three Website, Image and Finance fixtures show Compiler, CAL, SCBKR, R-Lock, VOID, verification gaps and an Action Gate.",
        boundaryZh: "沒有真實網站掃描、OCR、金融分析或私有權重運算；gate 與理由皆為預寫資料。",
        boundaryEn: "No real site scan, OCR, financial analysis or private-weight computation; gates and reasons are prewritten.",
        motionZh: "可無輸入輪播九案，但每幕必須標示 CURATED FIXTURE，不包裝成即時分析。",
        motionEn: "The nine cases can auto-play, but every scene must say CURATED FIXTURE rather than imply live analysis.",
        repo: "https://github.com/HIJO790401/SCBKR-WIF-Decision-Eligibility-Audit-Engine-Demo",
      },
      {
        code: "RG-04",
        titleZh: "TIRC 文件責任閘門",
        titleEn: "TIRC Document Responsibility Gate",
        status: "verified",
        statusZh: "本機後端可運行／前端需對齊",
        statusEn: "LOCAL BACKEND · FRONT-END ALIGNMENT NEEDED",
        actualZh: "本機版可讀 TXT／MD／PDF／DOCX，設定 T1–T3 actor policy，以六欄 ICC 閘門留下文件 hash 與 audit hash-chain。",
        actualEn: "The local build reads TXT, MD, PDF and DOCX, applies T1–T3 actor policy and records document and audit hashes through a six-field ICC gate.",
        boundaryZh: "不是完整 DLP／IAM／SSO，也不會自動攔外部平台；Pages 靜態 ICC 與後端的級距、分支尚未完全一致。",
        boundaryEn: "Not full DLP, IAM or SSO and does not intercept external platforms; the static ICC and backend scoring branches are not fully aligned.",
        motionZh: "只播放固定安全文件案例，不上傳訪客文件；畫面分開標示 LOCAL BACKEND 與 STATIC DEMO。",
        motionEn: "Play only a safe document fixture, upload no visitor file, and label LOCAL BACKEND and STATIC DEMO separately.",
        repo: "https://github.com/HIJO790401/TIRC-Document-Gate",
      },
      {
        code: "RG-05",
        titleZh: "WIF-Pay 付款責任防火牆",
        titleEn: "WIF-Pay Responsibility Firewall",
        status: "fixed",
        statusZh: "三個固定付款情境",
        statusEn: "THREE FIXED PAYMENT CASES",
        actualZh: "依手工預設向量計算 WIF、加權 SCBKR、Risk、責任節點，並在瀏覽器建立回放 hash-chain。",
        actualEn: "Hand-authored vectors feed WIF, weighted SCBKR, risk and liability-node calculations, plus a browser-generated replay hash chain.",
        boundaryZh: "不處理真實付款、不連銀行；不能稱為詐欺偵測、法律定責或不可竄改帳本。",
        boundaryEn: "It handles no real payment and connects to no bank; it is not fraud detection, legal attribution or an immutable ledger.",
        motionZh: "可依三個既有情境無輸入輪播，清楚標示 SIMULATED PAYMENT CASE。",
        motionEn: "Auto-play the three existing fixtures with a clear SIMULATED PAYMENT CASE label.",
        repo: "https://github.com/HIJO790401/Shen-Yao-WIF-Pay-Responsibility-Firewall",
      },
      {
        code: "RG-06",
        titleZh: "SLB 語意生命通道展示",
        titleEn: "SLB Semantic Life Bridge Display",
        status: "fixed",
        statusZh: "四個固定支持案例",
        statusEn: "FOUR FIXED SUPPORT CASES",
        actualZh: "四案呈現語意交集、記憶任務、輸出實現與責任邊界，內容包含預寫入口、下一步、三組向量與 replay。",
        actualEn: "Four cases present semantic overlap, memory tasks, output realization and responsibility boundaries with prewritten next steps, vectors and replay.",
        boundaryZh: "沒有自由輸入或實際分數計算；不是醫療診斷、治療、危機偵測或臨床驗證。",
        boundaryEn: "No free input or live score computation; not diagnosis, treatment, crisis detection or clinical validation.",
        motionZh: "只可播放既有固定案例，畫面永遠保留非醫療、非診斷邊界。",
        motionEn: "Only the existing fixtures may play, with non-medical and non-diagnostic boundaries always visible.",
        repo: "https://github.com/HIJO790401/shen-slb-demo",
      },
    ],
  },
  {
    id: "creative-media",
    index: "03",
    titleZh: "創作宇宙、哨兵與新聞台",
    titleEn: "Creative Universe, Sentinel & Newsroom",
    introZh: "這些不是後端治理產品；它們分別是視覺互動、前端模擬與媒體內容架構。官網會把三者留在正確位置。",
    introEn: "These are not backend governance products. They are visual interaction, front-end simulation and media architecture, each kept in its proper place.",
    products: [
      {
        code: "CM-01",
        titleZh: "沈靜流派創作宇宙",
        titleEn: "Serene School Creative Universe",
        status: "prototype",
        statusZh: "2D Canvas 視覺互動",
        statusEn: "2D CANVAS INTERACTION",
        actualZh: "單檔 Canvas 以冰／火雙核心、星空、連線、心形軌跡與滑鼠視差構成互動視覺。",
        actualEn: "A single Canvas file renders ice and fire cores, stars, links, heart-shaped paths and pointer parallax.",
        boundaryZh: "目前沒有 Three.js／WebGL 3D、音樂、後端或可查詢的作品星圖資料。",
        boundaryEn: "No Three.js or WebGL 3D, music, backend or queryable work-map data exists today.",
        motionZh: "保留真實 2D 核心，未來若升級 3D 必須另列新實作，不能把現況冒充 3D。",
        motionEn: "Preserve the real 2D core; any future 3D upgrade must be a new implementation, never a relabeling of the current state.",
        repo: "https://github.com/HIJO790401/shenjing-universe",
      },
      {
        code: "CM-02",
        titleZh: "SY Sentinel v1.1",
        titleEn: "SY Sentinel v1.1",
        status: "prototype",
        statusZh: "前端模擬展示",
        statusEn: "FRONT-END SIMULATION",
        actualZh: "以前端關鍵字命中、字數公式、13 軸顯示與 React state 日誌形成哨兵介面。",
        actualEn: "A sentinel interface built from keyword hits, text-length formulas, a 13-axis view and React-state logs.",
        boundaryZh: "部分 drift、compute load 與節省數據含 Math.random／公式假值；不是真監控、真攔截或 WORM 日誌。",
        boundaryEn: "Some drift, compute-load and saving values use randomness or formula placeholders; it is not real monitoring, blocking or WORM logging.",
        motionZh: "只能標示 SIMULATION；隨機數不作成效證據，也不在官網宣稱實測節省。",
        motionEn: "Label it SIMULATION; random values are never evidence and no measured savings will be claimed.",
        repo: "https://github.com/HIJO790401/SY-Sentinel-v1.1",
      },
      {
        code: "CM-03",
        titleZh: "國際實相新聞台／責任博物館",
        titleEn: "International Reality Newsroom & Responsibility Museum",
        status: "repair",
        statusZh: "內容架構重建中",
        statusEn: "CONTENT ARCHITECTURE REBUILD",
        actualZh: "原版為靜態 HTML／CSS／JS 加 Decap CMS，已有報導、館藏、職能工位與 YouTube 詳情頁嵌入結構。",
        actualEn: "The original is static HTML, CSS and JS with Decap CMS, reports, museum entries, role desks and YouTube embeds on detail pages.",
        boundaryZh: "部分職能影片使用不支援的 TikTok 個人頁；一支 YouTube 是待確認占位，不能冒充正式內容。",
        boundaryEn: "Some role videos point to unsupported TikTok profiles and one YouTube item is an unverified placeholder, so neither can be presented as official content.",
        motionZh: "新新聞台只採用可核實的 YouTube 嵌入；待確認素材清楚隔離，不污染官網主站。",
        motionEn: "The new newsroom embeds only verified YouTube media and isolates unconfirmed assets from the main studio site.",
        repo: "https://github.com/HIJO790401/shen-yao-reality-news-responsibility-museum",
      },
    ],
  },
];
