export type ProductFilm = {
  slug: string; index: string; name: string; nameEn: string; label: string;
  headlineZh: string; headlineEn: string; introZh: string; introEn: string;
  variant: "chain" | "firewall" | "rlock" | "copyright" | "memory" | "dual" | "compute" | "bridge" | "payment" | "universe" | "sentinel";
  formula: string; steps: Array<{ key: string; zh: string; en: string }>;
};

export const productFilms: ProductFilm[] = [
  { slug:"scbkr", index:"01", name:"SCBKR 本地責任鏈模型", nameEn:"SCBKR Local Responsibility Model", label:"LOCAL GOVERNANCE", headlineZh:"先把責任鏈接好，再允許系統行動。", headlineEn:"Connect responsibility before the system acts.", introZh:"本地工作台把主體、因果、邊界、依據與責任組成可回放的決策結構。", introEn:"A local workbench compiles subject, causality, boundary, key and responsibility into a replayable decision structure.", variant:"chain", formula:"S × C × B × K × R → CLOSE", steps:[{key:"S",zh:"鎖定真正主體",en:"Lock the actual subject"},{key:"B",zh:"建立可撤銷邊界",en:"Create revocable boundaries"},{key:"R",zh:"把結果接回具名責任",en:"Return outcomes to named responsibility"}] },
  { slug:"firewall-v4", index:"02", name:"語意防火牆 V4.1", nameEn:"Semantic Firewall V4.1", label:"LLM SAFETY LAYER", headlineZh:"模型回答之前與之後，都有一道可回放的防火牆。", headlineEn:"A replayable firewall before and after every model response.", introZh:"不改模型權重；以語意分析、風險偵測與稽核降低幻覺、高風險內容與推理浪費。", introEn:"Without changing model weights, semantic analysis, risk detection and audit reduce hallucination, high-risk content and inference waste.", variant:"firewall", formula:"INPUT → PRE-GATE → MODEL → POST-GATE → SAFE OUTPUT", steps:[{key:"01",zh:"輸入先掃描",en:"Scan input first"},{key:"02",zh:"模型輸出再審計",en:"Audit model output"},{key:"03",zh:"留下可回放判定",en:"Preserve a replayable verdict"}] },
  { slug:"anti-scam-rlock", index:"03", name:"反詐騙語意鎖 R-Lock", nameEn:"Anti-Scam Semantic R-Lock", label:"PRE-DECISION LOCK", headlineZh:"像官方，不代表有資格讓你做決定。", headlineEn:"Looking official does not qualify a message for action.", introZh:"在點擊、匯款或交付資料之前，先查主體、原因、成本與責任是否能被驗證。", introEn:"Before clicking, paying or sharing data, verify subject, cause, cost and responsibility.", variant:"rlock", formula:"UNVERIFIED STRUCTURE → R-LOCK → ACTION BLOCKED", steps:[{key:"S",zh:"寄件主體不可驗",en:"Sender cannot be verified"},{key:"K",zh:"依據與成本失真",en:"Evidence and cost are distorted"},{key:"R",zh:"無人承擔就鎖住行動",en:"No owner means action stays locked"}] },
  { slug:"copyright", index:"04", name:"著作權 SCBKR 責任邊界引擎", nameEn:"Copyright Responsibility-Boundary Engine", label:"LICENSE BOUNDARY", headlineZh:"不是有檔案就能用；要先看授權是否閉合。", headlineEn:"Possession is not permission; licensing must close.", introZh:"動畫展示作品、授權、使用模式與失效條件如何形成可追蹤的語意責任雜湊。", introEn:"See content, license, usage and failure conditions compile into a traceable semantic responsibility hash.", variant:"copyright", formula:"CONTENT × LICENSE × USE × RESPONSIBILITY → HASH", steps:[{key:"C",zh:"確認內容來源",en:"Confirm content source"},{key:"L",zh:"比對授權條件",en:"Match license conditions"},{key:"H",zh:"生成責任雜湊",en:"Generate responsibility hash"}] },
  { slug:"memory-index", index:"05", name:"SCBKR Memory Index", nameEn:"SCBKR Memory Index", label:"MEMORY ROUTING", headlineZh:"先整理記憶，再決定哪些能進入下一次判斷。", headlineEn:"Structure memory before it enters the next decision.", introZh:"跨來源記憶被索引、重播、稽核與截斷，只把具備責任鏈的內容送往下一層。", introEn:"Cross-source memory is indexed, replayed, audited and cut off before decision-ready records move forward.", variant:"memory", formula:"SOURCES → INDEX → CUTOFF → DECISION-READY MEMORY", steps:[{key:"01",zh:"多來源匯入",en:"Ingest many sources"},{key:"02",zh:"建立時間與責任索引",en:"Index time and responsibility"},{key:"03",zh:"不合格記憶停止前進",en:"Stop unqualified memory"}] },
  { slug:"dual-engine", index:"06", name:"語意防火牆雙引擎", nameEn:"Semantic Firewall Dual Engine", label:"TWO-LENS AUDIT", headlineZh:"同一件事，同時看法律責任與隱藏成本。", headlineEn:"One event, audited for legal responsibility and hidden cost.", introZh:"法律責任判決引擎與責任敘事成本引擎同步運行，最後在同一條責任鏈收束。", introEn:"A legal verdict engine and narrative-cost audit run together, then close on one responsibility chain.", variant:"dual", formula:"LEGAL VERDICT ∥ COST AUDIT → RESPONSIBILITY CLOSE", steps:[{key:"A",zh:"法律責任拆解",en:"Legal responsibility analysis"},{key:"B",zh:"隱藏與延後成本",en:"Hidden and deferred cost"},{key:"π",zh:"兩個結果交叉閉合",en:"Cross-close both outcomes"}] },
  { slug:"compute-governance", index:"07", name:"計算損失與提示治理引擎", nameEn:"Compute & Prompt Governance Engine", label:"PROMPT GOVERNANCE", headlineZh:"把語意污染、幻覺話術與算力浪費變成可見成本。", headlineEn:"Make semantic pollution, hallucination and compute waste visible.", introZh:"系統掃描提示與輸出，標記逃責語句、風險等級與推理浪費，形成可理解的治理結果。", introEn:"Prompts and outputs are scanned for responsibility evasion, risk grades and inference waste.", variant:"compute", formula:"PROMPT → POLLUTION SCAN → COST LOSS → REPAIR", steps:[{key:"01",zh:"掃描語意污染",en:"Scan semantic pollution"},{key:"02",zh:"估算浪費成本",en:"Estimate wasted compute"},{key:"03",zh:"產生修復方向",en:"Generate repair direction"}] },
  { slug:"semantic-life-bridge", index:"08", name:"沈耀語意生命通道", nameEn:"Shen-Yao Semantic Life Bridge", label:"CONTROLLED PRESET", headlineZh:"人不是標籤；真正需要補的是通道與責任鏈。", headlineEn:"A person is not a label; bridge the channel and responsibility.", introZh:"固定範本動畫，不診斷、不治療、不收集個資，展示標籤如何被重新接回通道、情境與責任。", introEn:"A controlled preset film—no diagnosis, treatment or data collection—bridging labels back to channel, context and responsibility.", variant:"bridge", formula:"PERSON ≠ LABEL → CHANNEL → CONTEXT → RESPONSIBILITY", steps:[{key:"P",zh:"人先於病名與標籤",en:"Person before label"},{key:"C",zh:"找出中斷的語意通道",en:"Find the broken channel"},{key:"R",zh:"用責任鏈穩定連接",en:"Stabilize with responsibility"}] },
  { slug:"wif-pay", index:"09", name:"WIF-Pay 金融責任鏈防火牆", nameEn:"WIF-Pay Responsibility Firewall", label:"PAYMENT REPLAY", headlineZh:"每一筆付款，都應該能知道發生什麼、誰要負責。", headlineEn:"Every payment should explain what happened and who owns it.", introZh:"不處理真實卡號；只展示銀行、平台、商家與客服之間的付款事件如何被記錄與回放。", introEn:"No real card data—only a film of how payment events move across banks, platforms, merchants and support.", variant:"payment", formula:"BANK → PLATFORM → SERVICE → SUPPORT → REPLAY", steps:[{key:"T",zh:"事件加上時間戳",en:"Timestamp the event"},{key:"S",zh:"跨服務追蹤狀態",en:"Trace status across services"},{key:"R",zh:"定位最終責任",en:"Locate final responsibility"}] },
  { slug:"shen-universe", index:"10", name:"沈靜流派創作宇宙", nameEn:"Silent School Creative Universe", label:"CREATIVE SYSTEM", headlineZh:"系統、動畫、音樂與族人，不再散落成孤島。", headlineEn:"Systems, animation, music and the clan become one connected universe.", introZh:"把技術作品、聲音、影像與世界觀整理成可探索、可持續擴張的創作星圖。", introEn:"Technology, sound, image and worldbuilding form an explorable, expandable creative constellation.", variant:"universe", formula:"SYSTEM × ANIMATION × MUSIC × STORY → UNIVERSE", steps:[{key:"S",zh:"系統作品成為核心星體",en:"Systems become core bodies"},{key:"A",zh:"動畫讓概念可見",en:"Animation makes concepts visible"},{key:"M",zh:"音樂與故事建立情感軌道",en:"Music and story form emotional orbits"}] },
  { slug:"sy-sentinel", index:"11", name:"SY Sentinel v1.1", nameEn:"SY Sentinel v1.1", label:"SEMANTIC SENTINEL", headlineZh:"先觀測，再攔截；每次阻擋都留下原因。", headlineEn:"Observe, intercept and preserve the reason for every block.", introZh:"哨兵持續觀測訊號、風險與責任缺口，將異常從行動路徑分離並保存回放紀錄。", introEn:"The sentinel observes signals, risk and responsibility gaps, separating anomalies from action while preserving replay.", variant:"sentinel", formula:"OBSERVE → DETECT → BLOCK → REPLAY", steps:[{key:"O",zh:"持續觀測訊號",en:"Observe signals"},{key:"D",zh:"偵測風險偏移",en:"Detect risk drift"},{key:"B",zh:"攔截並保存判定",en:"Block and preserve verdict"}] },
];

export function findFilm(slug: string) { return productFilms.find((film) => film.slug === slug); }
