import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const newsPosts = sqliteTable("news_posts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  slug: text("slug").notNull().unique(),
  titleZh: text("title_zh").notNull(),
  titleEn: text("title_en").notNull().default(""),
  summaryZh: text("summary_zh").notNull().default(""),
  summaryEn: text("summary_en").notNull().default(""),
  bodyZh: text("body_zh").notNull().default(""),
  bodyEn: text("body_en").notNull().default(""),
  category: text("category").notNull().default("REPORT"),
  coverUrl: text("cover_url").notNull().default(""),
  videoUrl: text("video_url").notNull().default(""),
  status: text("status").notNull().default("draft"),
  publishedAt: text("published_at").notNull(),
  updatedAt: text("updated_at").notNull(),
  authorEmail: text("author_email").notNull(),
}, (table) => [
  index("news_posts_status_date_idx").on(table.status, table.publishedAt),
]);

export const museumEntries = sqliteTable("museum_entries", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  slug: text("slug").notNull().unique(),
  registryId: text("registry_id").notNull().default(""),
  titleZh: text("title_zh").notNull(),
  titleEn: text("title_en").notNull().default(""),
  subtitleZh: text("subtitle_zh").notNull().default(""),
  subtitleEn: text("subtitle_en").notNull().default(""),
  guideZh: text("guide_zh").notNull().default(""),
  guideEn: text("guide_en").notNull().default(""),
  summaryZh: text("summary_zh").notNull().default(""),
  summaryEn: text("summary_en").notNull().default(""),
  bodyZh: text("body_zh").notNull().default(""),
  bodyEn: text("body_en").notNull().default(""),
  hallZh: text("hall_zh").notNull().default(""),
  hallEn: text("hall_en").notNull().default(""),
  verdictZh: text("verdict_zh").notNull().default(""),
  verdictEn: text("verdict_en").notNull().default(""),
  repairZh: text("repair_zh").notNull().default(""),
  repairEn: text("repair_en").notNull().default(""),
  evidenceUrl: text("evidence_url").notNull().default(""),
  coverUrl: text("cover_url").notNull().default(""),
  videoUrl: text("video_url").notNull().default(""),
  category: text("category").notNull().default("RESPONSIBILITY"),
  status: text("status").notNull().default("draft"),
  occurredAt: text("occurred_at").notNull(),
  updatedAt: text("updated_at").notNull(),
  authorEmail: text("author_email").notNull(),
}, (table) => [
  index("museum_entries_status_date_idx").on(table.status, table.occurredAt),
]);
